osx_image: xcode10.2

dist: trusty
sudo: false

language: node_js
node_js: "10"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release --linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release --mac --win; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"